language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"

install:
  - pip install -r requirements.txt --use-mirrors

before_script:
  - pep8 righteous
  - pyflakes righteous

script:
  - testify tests.unit
